// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AutomationEventList {
 *     unsigned int capacity;
 *     unsigned int count;
 *     AutomationEvent* events;
 * };
 * }
 */
public class AutomationEventList {

    public static MemoryLayout $LAYOUT() {
        return constants$26.const$1;
    }
    public static VarHandle capacity$VH() {
        return constants$26.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int capacity;
     * }
     */
    public static int capacity$get(MemorySegment seg) {
        return (int)constants$26.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int capacity;
     * }
     */
    public static void capacity$set(MemorySegment seg, int x) {
        constants$26.const$2.set(seg, x);
    }
    public static int capacity$get(MemorySegment seg, long index) {
        return (int)constants$26.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void capacity$set(MemorySegment seg, long index, int x) {
        constants$26.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle count$VH() {
        return constants$26.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int count;
     * }
     */
    public static int count$get(MemorySegment seg) {
        return (int)constants$26.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int count;
     * }
     */
    public static void count$set(MemorySegment seg, int x) {
        constants$26.const$3.set(seg, x);
    }
    public static int count$get(MemorySegment seg, long index) {
        return (int)constants$26.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, int x) {
        constants$26.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle events$VH() {
        return constants$26.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * AutomationEvent* events;
     * }
     */
    public static MemorySegment events$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$26.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * AutomationEvent* events;
     * }
     */
    public static void events$set(MemorySegment seg, MemorySegment x) {
        constants$26.const$4.set(seg, x);
    }
    public static MemorySegment events$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$26.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void events$set(MemorySegment seg, long index, MemorySegment x) {
        constants$26.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


