// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$157 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$157() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "PauseMusicStream",
        constants$156.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ResumeMusicStream",
        constants$156.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("buffer"),
                RuntimeHelper.POINTER.withName("processor"),
                JAVA_INT.withName("sampleRate"),
                JAVA_INT.withName("sampleSize"),
                JAVA_INT.withName("channels"),
                MemoryLayout.paddingLayout(4)
            ).withName("stream"),
            JAVA_INT.withName("frameCount"),
            JAVA_BOOLEAN.withName("looping"),
            MemoryLayout.paddingLayout(3),
            JAVA_INT.withName("ctxType"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("ctxData")
        ).withName("Music"),
        JAVA_FLOAT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SeekMusicStream",
        constants$157.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SetMusicVolume",
        constants$157.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SetMusicPitch",
        constants$157.const$2
    );
}


