// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$114 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$114() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_BYTE.withName("r"),
        JAVA_BYTE.withName("g"),
        JAVA_BYTE.withName("b"),
        JAVA_BYTE.withName("a")
    ).withName("Color"),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color"),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ColorTint",
        constants$114.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ColorBrightness",
        constants$112.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ColorContrast",
        constants$112.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ColorAlpha",
        constants$112.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_BYTE.withName("r"),
        JAVA_BYTE.withName("g"),
        JAVA_BYTE.withName("b"),
        JAVA_BYTE.withName("a")
    ).withName("Color"),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color"),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color"),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ColorAlphaBlend",
        constants$114.const$5
    );
}


