// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final VarHandle const$0 = constants$20.const$1.varHandle(MemoryLayout.PathElement.groupElement("data"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("processor"),
        JAVA_INT.withName("sampleRate"),
        JAVA_INT.withName("sampleSize"),
        JAVA_INT.withName("channels"),
        MemoryLayout.paddingLayout(4)
    ).withName("AudioStream");
    static final VarHandle const$2 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("buffer"));
    static final VarHandle const$3 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("processor"));
    static final VarHandle const$4 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("sampleRate"));
    static final VarHandle const$5 = constants$21.const$1.varHandle(MemoryLayout.PathElement.groupElement("sampleSize"));
}


