// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$161 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$161() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("buffer"),
            RuntimeHelper.POINTER.withName("processor"),
            JAVA_INT.withName("sampleRate"),
            JAVA_INT.withName("sampleSize"),
            JAVA_INT.withName("channels"),
            MemoryLayout.paddingLayout(4)
        ).withName("AudioStream"),
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetAudioStreamVolume",
        constants$161.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SetAudioStreamPitch",
        constants$161.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SetAudioStreamPan",
        constants$161.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SetAudioStreamBufferSizeDefault",
        constants$31.const$5
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("buffer"),
            RuntimeHelper.POINTER.withName("processor"),
            JAVA_INT.withName("sampleRate"),
            JAVA_INT.withName("sampleSize"),
            JAVA_INT.withName("channels"),
            MemoryLayout.paddingLayout(4)
        ).withName("AudioStream"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "SetAudioStreamCallback",
        constants$161.const$5
    );
}


