// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$56 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$56() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "DirectoryExists",
        constants$55.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IsFileExtension",
        constants$28.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetFileLength",
        constants$56.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetFileExtension",
        constants$28.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetFileName",
        constants$28.const$2
    );
}


