// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$129 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$129() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "DrawTriangleStrip3D",
        constants$73.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("Vector3"),
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT,
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color")
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "DrawCube",
        constants$129.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "DrawCubeV",
        constants$127.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "DrawCubeWires",
        constants$129.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "DrawCubeWiresV",
        constants$127.const$5
    );
}


