// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$152 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$152() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ExportWaveAsCode",
        constants$151.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "PlaySound",
        constants$151.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "StopSound",
        constants$151.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "PauseSound",
        constants$151.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ResumeSound",
        constants$151.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "IsSoundPlaying",
        constants$150.const$2
    );
}


