// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$81 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$81() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "DrawSplineCatmullRom",
        constants$80.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DrawSplineBezierQuadratic",
        constants$80.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "DrawSplineBezierCubic",
        constants$80.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "DrawSplineSegmentLinear",
        constants$72.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("Vector2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("Vector2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("Vector2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("Vector2"),
        JAVA_FLOAT,
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "DrawSplineSegmentBasis",
        constants$81.const$4
    );
}


