// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$154 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$154() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "WaveCrop",
        constants$97.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "WaveFormat",
        constants$154.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("frameCount"),
            JAVA_INT.withName("sampleRate"),
            JAVA_INT.withName("sampleSize"),
            JAVA_INT.withName("channels"),
            RuntimeHelper.POINTER.withName("data")
        ).withName("Wave")
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "LoadWaveSamples",
        constants$154.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "UnloadWaveSamples",
        constants$33.const$4
    );
}


