// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("capacity"),
        JAVA_INT.withName("count"),
        RuntimeHelper.POINTER.withName("paths")
    ).withName("FilePathList");
    static final VarHandle const$1 = constants$25.const$0.varHandle(MemoryLayout.PathElement.groupElement("capacity"));
    static final VarHandle const$2 = constants$25.const$0.varHandle(MemoryLayout.PathElement.groupElement("count"));
    static final VarHandle const$3 = constants$25.const$0.varHandle(MemoryLayout.PathElement.groupElement("paths"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("frame"),
        JAVA_INT.withName("type"),
        MemoryLayout.sequenceLayout(4, JAVA_INT).withName("params")
    ).withName("AutomationEvent");
    static final VarHandle const$5 = constants$25.const$4.varHandle(MemoryLayout.PathElement.groupElement("frame"));
}


