// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final VarHandle const$0 = constants$2.const$0.varHandle(MemoryLayout.PathElement.groupElement("m14"));
    static final VarHandle const$1 = constants$2.const$0.varHandle(MemoryLayout.PathElement.groupElement("m3"));
    static final VarHandle const$2 = constants$2.const$0.varHandle(MemoryLayout.PathElement.groupElement("m7"));
    static final VarHandle const$3 = constants$2.const$0.varHandle(MemoryLayout.PathElement.groupElement("m11"));
    static final VarHandle const$4 = constants$2.const$0.varHandle(MemoryLayout.PathElement.groupElement("m15"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("r"),
        JAVA_BYTE.withName("g"),
        JAVA_BYTE.withName("b"),
        JAVA_BYTE.withName("a")
    ).withName("Color");
}


