// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final VarHandle const$0 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("height"));
    static final VarHandle const$1 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("mipmaps"));
    static final VarHandle const$2 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("format"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("id"),
        JAVA_INT.withName("width"),
        JAVA_INT.withName("height"),
        JAVA_INT.withName("mipmaps"),
        JAVA_INT.withName("format")
    ).withName("Texture");
    static final VarHandle const$4 = constants$7.const$3.varHandle(MemoryLayout.PathElement.groupElement("id"));
    static final VarHandle const$5 = constants$7.const$3.varHandle(MemoryLayout.PathElement.groupElement("width"));
}


