// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$158 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$158() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SetMusicPan",
        constants$157.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_FLOAT,
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("buffer"),
                RuntimeHelper.POINTER.withName("processor"),
                JAVA_INT.withName("sampleRate"),
                JAVA_INT.withName("sampleSize"),
                JAVA_INT.withName("channels"),
                MemoryLayout.paddingLayout(4)
            ).withName("stream"),
            JAVA_INT.withName("frameCount"),
            JAVA_BOOLEAN.withName("looping"),
            MemoryLayout.paddingLayout(3),
            JAVA_INT.withName("ctxType"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("ctxData")
        ).withName("Music")
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "GetMusicTimeLength",
        constants$158.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetMusicTimePlayed",
        constants$158.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("processor"),
        JAVA_INT.withName("sampleRate"),
        JAVA_INT.withName("sampleSize"),
        JAVA_INT.withName("channels"),
        MemoryLayout.paddingLayout(4)
    ).withName("AudioStream"),
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "LoadAudioStream",
        constants$158.const$4
    );
}


