// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$76 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$76() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "DrawRingLines",
        constants$75.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DrawRectangle",
        constants$72.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "DrawRectangleV",
        constants$72.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("width"),
            JAVA_FLOAT.withName("height")
        ).withName("Rectangle"),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color")
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "DrawRectangleRec",
        constants$76.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("width"),
            JAVA_FLOAT.withName("height")
        ).withName("Rectangle"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("Vector2"),
        JAVA_FLOAT,
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "DrawRectanglePro",
        constants$76.const$5
    );
}


