// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$64 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$64() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetGamepadName",
        constants$38.const$3
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_BOOLEAN,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IsGamepadButtonPressed",
        constants$64.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "IsGamepadButtonDown",
        constants$64.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "IsGamepadButtonReleased",
        constants$64.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "IsGamepadButtonUp",
        constants$64.const$1
    );
}


