// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$69 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$69() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetTouchPointCount",
        constants$35.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetGesturesEnabled",
        constants$31.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IsGestureDetected",
        constants$31.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetGestureDetected",
        constants$35.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetGestureHoldDuration",
        constants$49.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetGestureDragVector",
        constants$38.const$0
    );
}


