// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$123 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$123() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "LoadUTF8",
        constants$53.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "UnloadUTF8",
        constants$33.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "LoadCodepoints",
        constants$27.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "UnloadCodepoints",
        constants$33.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetCodepointCount",
        constants$56.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "GetCodepoint",
        constants$123.const$5
    );
}


