// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$143 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$143() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("id"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("mipmaps"),
            JAVA_INT.withName("format")
        ).withName("Texture")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetMaterialTexture",
        constants$143.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SetModelMeshMaterial",
        constants$97.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "LoadModelAnimations",
        constants$27.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("m0"),
                JAVA_FLOAT.withName("m4"),
                JAVA_FLOAT.withName("m8"),
                JAVA_FLOAT.withName("m12"),
                JAVA_FLOAT.withName("m1"),
                JAVA_FLOAT.withName("m5"),
                JAVA_FLOAT.withName("m9"),
                JAVA_FLOAT.withName("m13"),
                JAVA_FLOAT.withName("m2"),
                JAVA_FLOAT.withName("m6"),
                JAVA_FLOAT.withName("m10"),
                JAVA_FLOAT.withName("m14"),
                JAVA_FLOAT.withName("m3"),
                JAVA_FLOAT.withName("m7"),
                JAVA_FLOAT.withName("m11"),
                JAVA_FLOAT.withName("m15")
            ).withName("transform"),
            JAVA_INT.withName("meshCount"),
            JAVA_INT.withName("materialCount"),
            RuntimeHelper.POINTER.withName("meshes"),
            RuntimeHelper.POINTER.withName("materials"),
            RuntimeHelper.POINTER.withName("meshMaterial"),
            JAVA_INT.withName("boneCount"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("bones"),
            RuntimeHelper.POINTER.withName("bindPose")
        ).withName("Model"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("boneCount"),
            JAVA_INT.withName("frameCount"),
            RuntimeHelper.POINTER.withName("bones"),
            RuntimeHelper.POINTER.withName("framePoses"),
            MemoryLayout.sequenceLayout(32, JAVA_BYTE).withName("name")
        ).withName("ModelAnimation"),
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "UpdateModelAnimation",
        constants$143.const$4
    );
}


