// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final VarHandle const$0 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("glyphCount"));
    static final VarHandle const$1 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("glyphPadding"));
    static final VarHandle const$2 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("recs"));
    static final VarHandle const$3 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("glyphs"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("position"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("target"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("up"),
        JAVA_FLOAT.withName("fovy"),
        JAVA_INT.withName("projection")
    ).withName("Camera3D");
    static final VarHandle const$5 = constants$11.const$4.varHandle(MemoryLayout.PathElement.groupElement("fovy"));
}


