// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_FLOAT.withName("m0"),
        JAVA_FLOAT.withName("m4"),
        JAVA_FLOAT.withName("m8"),
        JAVA_FLOAT.withName("m12"),
        JAVA_FLOAT.withName("m1"),
        JAVA_FLOAT.withName("m5"),
        JAVA_FLOAT.withName("m9"),
        JAVA_FLOAT.withName("m13"),
        JAVA_FLOAT.withName("m2"),
        JAVA_FLOAT.withName("m6"),
        JAVA_FLOAT.withName("m10"),
        JAVA_FLOAT.withName("m14"),
        JAVA_FLOAT.withName("m3"),
        JAVA_FLOAT.withName("m7"),
        JAVA_FLOAT.withName("m11"),
        JAVA_FLOAT.withName("m15")
    ).withName("Matrix"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("offset"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("target"),
            JAVA_FLOAT.withName("rotation"),
            JAVA_FLOAT.withName("zoom")
        ).withName("Camera2D")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "GetCameraMatrix2D",
        constants$48.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y")
    ).withName("Vector2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("Vector3"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("position"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("target"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("up"),
            JAVA_FLOAT.withName("fovy"),
            JAVA_INT.withName("projection")
        ).withName("Camera3D")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetWorldToScreen",
        constants$48.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y")
    ).withName("Vector2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("Vector2"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("offset"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("target"),
            JAVA_FLOAT.withName("rotation"),
            JAVA_FLOAT.withName("zoom")
        ).withName("Camera2D")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetScreenToWorld2D",
        constants$48.const$4
    );
}


