// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final VarHandle const$0 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("triangleCount"));
    static final VarHandle const$1 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("vertices"));
    static final VarHandle const$2 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("texcoords"));
    static final VarHandle const$3 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("texcoords2"));
    static final VarHandle const$4 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("normals"));
    static final VarHandle const$5 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("tangents"));
}


