// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ClearWindowState",
        constants$31.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ToggleFullscreen",
        constants$29.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ToggleBorderlessWindowed",
        constants$29.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "MaximizeWindow",
        constants$29.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "MinimizeWindow",
        constants$29.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "RestoreWindow",
        constants$29.const$4
    );
}


