// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final VarHandle const$0 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("r"));
    static final VarHandle const$1 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("g"));
    static final VarHandle const$2 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("b"));
    static final VarHandle const$3 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("a"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y"),
        JAVA_FLOAT.withName("width"),
        JAVA_FLOAT.withName("height")
    ).withName("Rectangle");
    static final VarHandle const$5 = constants$5.const$4.varHandle(MemoryLayout.PathElement.groupElement("x"));
}


