// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$11.const$4.varHandle(MemoryLayout.PathElement.groupElement("projection"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("offset"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("target"),
        JAVA_FLOAT.withName("rotation"),
        JAVA_FLOAT.withName("zoom")
    ).withName("Camera2D");
    static final VarHandle const$2 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("rotation"));
    static final VarHandle const$3 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("zoom"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("vertexCount"),
        JAVA_INT.withName("triangleCount"),
        RuntimeHelper.POINTER.withName("vertices"),
        RuntimeHelper.POINTER.withName("texcoords"),
        RuntimeHelper.POINTER.withName("texcoords2"),
        RuntimeHelper.POINTER.withName("normals"),
        RuntimeHelper.POINTER.withName("tangents"),
        RuntimeHelper.POINTER.withName("colors"),
        RuntimeHelper.POINTER.withName("indices"),
        RuntimeHelper.POINTER.withName("animVertices"),
        RuntimeHelper.POINTER.withName("animNormals"),
        RuntimeHelper.POINTER.withName("boneIds"),
        RuntimeHelper.POINTER.withName("boneWeights"),
        JAVA_INT.withName("vaoId"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("vboId")
    ).withName("Mesh");
    static final VarHandle const$5 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("vertexCount"));
}


