// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$58 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$58() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "IsPathFile",
        constants$55.const$5
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("capacity"),
        JAVA_INT.withName("count"),
        RuntimeHelper.POINTER.withName("paths")
    ).withName("FilePathList"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "LoadDirectoryFiles",
        constants$58.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("capacity"),
        JAVA_INT.withName("count"),
        RuntimeHelper.POINTER.withName("paths")
    ).withName("FilePathList"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "LoadDirectoryFilesEx",
        constants$58.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("capacity"),
            JAVA_INT.withName("count"),
            RuntimeHelper.POINTER.withName("paths")
        ).withName("FilePathList")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "UnloadDirectoryFiles",
        constants$58.const$5
    );
}


