// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("id"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("locs")
        ).withName("Shader"),
        JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("id"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("mipmaps"),
            JAVA_INT.withName("format")
        ).withName("Texture")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetShaderValueTexture",
        constants$47.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "UnloadShader",
        constants$42.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("position"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("direction")
    ).withName("Ray"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("Vector2"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("position"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("target"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("up"),
            JAVA_FLOAT.withName("fovy"),
            JAVA_INT.withName("projection")
        ).withName("Camera3D")
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetMouseRay",
        constants$47.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_FLOAT.withName("m0"),
        JAVA_FLOAT.withName("m4"),
        JAVA_FLOAT.withName("m8"),
        JAVA_FLOAT.withName("m12"),
        JAVA_FLOAT.withName("m1"),
        JAVA_FLOAT.withName("m5"),
        JAVA_FLOAT.withName("m9"),
        JAVA_FLOAT.withName("m13"),
        JAVA_FLOAT.withName("m2"),
        JAVA_FLOAT.withName("m6"),
        JAVA_FLOAT.withName("m10"),
        JAVA_FLOAT.withName("m14"),
        JAVA_FLOAT.withName("m3"),
        JAVA_FLOAT.withName("m7"),
        JAVA_FLOAT.withName("m11"),
        JAVA_FLOAT.withName("m15")
    ).withName("Matrix"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("position"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("target"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("up"),
            JAVA_FLOAT.withName("fovy"),
            JAVA_INT.withName("projection")
        ).withName("Camera3D")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "GetCameraMatrix",
        constants$47.const$5
    );
}


