// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "TakeScreenshot",
        constants$33.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetConfigFlags",
        constants$31.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "OpenURL",
        constants$33.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "TraceLog",
        constants$52.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SetTraceLogLevel",
        constants$31.const$5
    );
}


