// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final VarHandle const$0 = constants$18.const$3.varHandle(MemoryLayout.PathElement.groupElement("bones"));
    static final VarHandle const$1 = constants$18.const$3.varHandle(MemoryLayout.PathElement.groupElement("framePoses"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("position"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("direction")
    ).withName("Ray");
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_BOOLEAN.withName("hit"),
        MemoryLayout.paddingLayout(3),
        JAVA_FLOAT.withName("distance"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("point"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("normal")
    ).withName("RayCollision");
    static final VarHandle const$4 = constants$19.const$3.varHandle(MemoryLayout.PathElement.groupElement("hit"));
    static final VarHandle const$5 = constants$19.const$3.varHandle(MemoryLayout.PathElement.groupElement("distance"));
}


