// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$98 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$98() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ImageDither",
        constants$98.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ImageFlipVertical",
        constants$33.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ImageFlipHorizontal",
        constants$33.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ImageRotate",
        constants$33.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ImageRotateCW",
        constants$33.const$4
    );
}


