// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$67 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$67() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetMouseDelta",
        constants$38.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetMousePosition",
        constants$34.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SetMouseOffset",
        constants$34.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SetMouseScale",
        constants$67.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetMouseWheelMove",
        constants$49.const$4
    );
}


