// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "EndShaderMode",
        constants$29.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "BeginBlendMode",
        constants$31.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "EndBlendMode",
        constants$29.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "BeginScissorMode",
        constants$43.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "EndScissorMode",
        constants$29.const$4
    );
}


