// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$66 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$66() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "IsMouseButtonDown",
        constants$31.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IsMouseButtonReleased",
        constants$31.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IsMouseButtonUp",
        constants$31.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetMouseX",
        constants$35.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetMouseY",
        constants$35.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetMousePosition",
        constants$38.const$0
    );
}


