// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$65 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$65() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetGamepadButtonPressed",
        constants$35.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "GetGamepadAxisCount",
        constants$37.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetGamepadAxisMovement",
        constants$65.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SetGamepadMappings",
        constants$56.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "IsMouseButtonPressed",
        constants$31.const$3
    );
}


