// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct MaterialMap {
 *     Texture2D texture;
 *     Color color;
 *     float value;
 * };
 * }
 */
public class MaterialMap {

    public static MemoryLayout $LAYOUT() {
        return constants$15.const$5;
    }
    public static MemorySegment texture$slice(MemorySegment seg) {
        return seg.asSlice(0, 20);
    }
    public static MemorySegment color$slice(MemorySegment seg) {
        return seg.asSlice(20, 4);
    }
    public static VarHandle value$VH() {
        return constants$16.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float value;
     * }
     */
    public static float value$get(MemorySegment seg) {
        return (float)constants$16.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float value;
     * }
     */
    public static void value$set(MemorySegment seg, float x) {
        constants$16.const$0.set(seg, x);
    }
    public static float value$get(MemorySegment seg, long index) {
        return (float)constants$16.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void value$set(MemorySegment seg, long index, float x) {
        constants$16.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


