// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Music {
 *     AudioStream stream;
 *     unsigned int frameCount;
 *     _Bool looping;
 *     int ctxType;
 *     void* ctxData;
 * };
 * }
 */
public class Music {

    public static MemoryLayout $LAYOUT() {
        return constants$22.const$3;
    }
    public static MemorySegment stream$slice(MemorySegment seg) {
        return seg.asSlice(0, 32);
    }
    public static VarHandle frameCount$VH() {
        return constants$22.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int frameCount;
     * }
     */
    public static int frameCount$get(MemorySegment seg) {
        return (int)constants$22.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int frameCount;
     * }
     */
    public static void frameCount$set(MemorySegment seg, int x) {
        constants$22.const$4.set(seg, x);
    }
    public static int frameCount$get(MemorySegment seg, long index) {
        return (int)constants$22.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void frameCount$set(MemorySegment seg, long index, int x) {
        constants$22.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle looping$VH() {
        return constants$22.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool looping;
     * }
     */
    public static boolean looping$get(MemorySegment seg) {
        return (boolean)constants$22.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool looping;
     * }
     */
    public static void looping$set(MemorySegment seg, boolean x) {
        constants$22.const$5.set(seg, x);
    }
    public static boolean looping$get(MemorySegment seg, long index) {
        return (boolean)constants$22.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void looping$set(MemorySegment seg, long index, boolean x) {
        constants$22.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ctxType$VH() {
        return constants$23.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int ctxType;
     * }
     */
    public static int ctxType$get(MemorySegment seg) {
        return (int)constants$23.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int ctxType;
     * }
     */
    public static void ctxType$set(MemorySegment seg, int x) {
        constants$23.const$0.set(seg, x);
    }
    public static int ctxType$get(MemorySegment seg, long index) {
        return (int)constants$23.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void ctxType$set(MemorySegment seg, long index, int x) {
        constants$23.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ctxData$VH() {
        return constants$23.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* ctxData;
     * }
     */
    public static MemorySegment ctxData$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$23.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* ctxData;
     * }
     */
    public static void ctxData$set(MemorySegment seg, MemorySegment x) {
        constants$23.const$1.set(seg, x);
    }
    public static MemorySegment ctxData$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$23.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void ctxData$set(MemorySegment seg, long index, MemorySegment x) {
        constants$23.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


