// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct RayCollision {
 *     _Bool hit;
 *     float distance;
 *     Vector3 point;
 *     Vector3 normal;
 * };
 * }
 */
public class RayCollision {

    public static MemoryLayout $LAYOUT() {
        return constants$19.const$3;
    }
    public static VarHandle hit$VH() {
        return constants$19.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool hit;
     * }
     */
    public static boolean hit$get(MemorySegment seg) {
        return (boolean)constants$19.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool hit;
     * }
     */
    public static void hit$set(MemorySegment seg, boolean x) {
        constants$19.const$4.set(seg, x);
    }
    public static boolean hit$get(MemorySegment seg, long index) {
        return (boolean)constants$19.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void hit$set(MemorySegment seg, long index, boolean x) {
        constants$19.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle distance$VH() {
        return constants$19.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float distance;
     * }
     */
    public static float distance$get(MemorySegment seg) {
        return (float)constants$19.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float distance;
     * }
     */
    public static void distance$set(MemorySegment seg, float x) {
        constants$19.const$5.set(seg, x);
    }
    public static float distance$get(MemorySegment seg, long index) {
        return (float)constants$19.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void distance$set(MemorySegment seg, long index, float x) {
        constants$19.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment point$slice(MemorySegment seg) {
        return seg.asSlice(8, 12);
    }
    public static MemorySegment normal$slice(MemorySegment seg) {
        return seg.asSlice(20, 12);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


