// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Shader {
 *     unsigned int id;
 *     int* locs;
 * };
 * }
 */
public class Shader {

    public static MemoryLayout $LAYOUT() {
        return constants$15.const$2;
    }
    public static VarHandle id$VH() {
        return constants$15.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int id;
     * }
     */
    public static int id$get(MemorySegment seg) {
        return (int)constants$15.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int id;
     * }
     */
    public static void id$set(MemorySegment seg, int x) {
        constants$15.const$3.set(seg, x);
    }
    public static int id$get(MemorySegment seg, long index) {
        return (int)constants$15.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void id$set(MemorySegment seg, long index, int x) {
        constants$15.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle locs$VH() {
        return constants$15.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int* locs;
     * }
     */
    public static MemorySegment locs$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$15.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int* locs;
     * }
     */
    public static void locs$set(MemorySegment seg, MemorySegment x) {
        constants$15.const$4.set(seg, x);
    }
    public static MemorySegment locs$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$15.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void locs$set(MemorySegment seg, long index, MemorySegment x) {
        constants$15.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


