// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct Texture TextureCubemap;
 * }
 */
public final class TextureCubemap extends Texture {

    // Suppresses default constructor, ensuring non-instantiability.
    private TextureCubemap() {}
}


