// Generated by jextract

package raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Transform {
 *     Vector3 translation;
 *     Quaternion rotation;
 *     Vector3 scale;
 * };
 * }
 */
public class Transform {

    public static MemoryLayout $LAYOUT() {
        return constants$16.const$3;
    }
    public static MemorySegment translation$slice(MemorySegment seg) {
        return seg.asSlice(0, 12);
    }
    public static MemorySegment rotation$slice(MemorySegment seg) {
        return seg.asSlice(12, 16);
    }
    public static MemorySegment scale$slice(MemorySegment seg) {
        return seg.asSlice(28, 12);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


