// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlDisableVertexBufferElement",
        constants$6.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlEnableVertexAttribute",
        constants$6.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlDisableVertexAttribute",
        constants$6.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlActiveTextureSlot",
        constants$6.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlEnableTexture",
        constants$6.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlDisableTexture",
        constants$6.const$2
    );
}


