// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final VarHandle const$0 = constants$2.const$5.varHandle(MemoryLayout.PathElement.groupElement("elementCount"));
    static final VarHandle const$1 = constants$2.const$5.varHandle(MemoryLayout.PathElement.groupElement("vertices"));
    static final VarHandle const$2 = constants$2.const$5.varHandle(MemoryLayout.PathElement.groupElement("texcoords"));
    static final VarHandle const$3 = constants$2.const$5.varHandle(MemoryLayout.PathElement.groupElement("colors"));
    static final VarHandle const$4 = constants$2.const$5.varHandle(MemoryLayout.PathElement.groupElement("indices"));
    static final VarHandle const$5 = constants$2.const$5.varHandle(MemoryLayout.PathElement.groupElement("vaoId"));
}


