// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlLoadVertexBufferElement",
        constants$23.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlUpdateVertexBuffer",
        constants$24.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlUpdateVertexBufferElements",
        constants$24.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlUnloadVertexArray",
        constants$6.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlUnloadVertexBuffer",
        constants$6.const$0
    );
}


