// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("m0"),
        JAVA_FLOAT.withName("m4"),
        JAVA_FLOAT.withName("m8"),
        JAVA_FLOAT.withName("m12"),
        JAVA_FLOAT.withName("m1"),
        JAVA_FLOAT.withName("m5"),
        JAVA_FLOAT.withName("m9"),
        JAVA_FLOAT.withName("m13"),
        JAVA_FLOAT.withName("m2"),
        JAVA_FLOAT.withName("m6"),
        JAVA_FLOAT.withName("m10"),
        JAVA_FLOAT.withName("m14"),
        JAVA_FLOAT.withName("m3"),
        JAVA_FLOAT.withName("m7"),
        JAVA_FLOAT.withName("m11"),
        JAVA_FLOAT.withName("m15")
    ).withName("Matrix");
    static final VarHandle const$1 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("m0"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("m4"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("m8"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("m12"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("m1"));
}


