// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlEnableBackfaceCulling",
        constants$6.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlDisableBackfaceCulling",
        constants$6.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlSetCullFace",
        constants$6.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlEnableScissorTest",
        constants$6.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlDisableScissorTest",
        constants$6.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlScissor",
        constants$8.const$3
    );
}


