// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("bufferCount"),
        JAVA_INT.withName("currentBuffer"),
        RuntimeHelper.POINTER.withName("vertexBuffer"),
        RuntimeHelper.POINTER.withName("draws"),
        JAVA_INT.withName("drawCounter"),
        JAVA_FLOAT.withName("currentDepth")
    ).withName("rlRenderBatch"),
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlLoadRenderBatch",
        constants$22.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("bufferCount"),
            JAVA_INT.withName("currentBuffer"),
            RuntimeHelper.POINTER.withName("vertexBuffer"),
            RuntimeHelper.POINTER.withName("draws"),
            JAVA_INT.withName("drawCounter"),
            JAVA_FLOAT.withName("currentDepth")
        ).withName("rlRenderBatch")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlUnloadRenderBatch",
        constants$22.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlDrawRenderBatch",
        constants$7.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlSetRenderBatchActive",
        constants$7.const$5
    );
}


