// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlEnd",
        constants$6.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlVertex2i",
        constants$9.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlVertex2f",
        constants$9.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlVertex3f",
        constants$7.const$0
    );
}


