// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlReadShaderBuffer",
        constants$24.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlCopyShaderBuffer",
        constants$29.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlGetShaderBufferSize",
        constants$32.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlBindImageTexture",
        constants$34.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_FLOAT.withName("m0"),
        JAVA_FLOAT.withName("m4"),
        JAVA_FLOAT.withName("m8"),
        JAVA_FLOAT.withName("m12"),
        JAVA_FLOAT.withName("m1"),
        JAVA_FLOAT.withName("m5"),
        JAVA_FLOAT.withName("m9"),
        JAVA_FLOAT.withName("m13"),
        JAVA_FLOAT.withName("m2"),
        JAVA_FLOAT.withName("m6"),
        JAVA_FLOAT.withName("m10"),
        JAVA_FLOAT.withName("m14"),
        JAVA_FLOAT.withName("m3"),
        JAVA_FLOAT.withName("m7"),
        JAVA_FLOAT.withName("m11"),
        JAVA_FLOAT.withName("m15")
    ).withName("Matrix"));
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "rlGetMatrixModelview",
        constants$34.const$5
    );
}


