// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlTexCoord2f",
        constants$9.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlNormal3f",
        constants$7.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        JAVA_BYTE,
        JAVA_BYTE,
        JAVA_BYTE,
        JAVA_BYTE
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlColor4ub",
        constants$10.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlColor3f",
        constants$7.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlColor4f",
        constants$7.const$2
    );
}


