// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlGetFramebufferWidth",
        constants$20.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlSetFramebufferHeight",
        constants$6.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlGetFramebufferHeight",
        constants$20.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlGetTextureIdDefault",
        constants$20.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlGetShaderIdDefault",
        constants$20.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "rlGetShaderLocsDefault",
        constants$21.const$5
    );
}


