// Generated by jextract

package rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlLoadShaderProgram",
        constants$29.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlUnloadShaderProgram",
        constants$6.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlGetLocationUniform",
        constants$31.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlGetLocationAttrib",
        constants$31.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlSetUniform",
        constants$24.const$1
    );
}


