// Generated by jextract

package rayclj.rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlMatrixMode",
        constants$6.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlPushMatrix",
        constants$6.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlPopMatrix",
        constants$6.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlLoadIdentity",
        constants$6.const$2
    );
}


