// Generated by jextract

package rayclj.rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlglInit",
        constants$9.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlglClose",
        constants$6.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlLoadExtensions",
        constants$7.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlGetVersion",
        constants$20.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlSetFramebufferWidth",
        constants$6.const$0
    );
}


