// Generated by jextract

package rayclj.rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rlEnableWireMode",
        constants$6.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlEnablePointMode",
        constants$6.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlDisableWireMode",
        constants$6.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlSetLineWidth",
        constants$17.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_FLOAT);
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "rlGetLineWidth",
        constants$17.const$5
    );
}


