// Generated by jextract

package rayclj.rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_BOOLEAN,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlEnableVertexArray",
        constants$11.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlDisableVertexArray",
        constants$6.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlEnableVertexBuffer",
        constants$6.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlDisableVertexBuffer",
        constants$6.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "rlEnableVertexBufferElement",
        constants$6.const$0
    );
}


