// Generated by jextract

package rayclj.rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_BOOLEAN,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rlSetVertexAttribute",
        constants$25.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "rlSetVertexAttributeDivisor",
        constants$9.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "rlSetVertexAttributeDefault",
        constants$24.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "rlDrawVertexArray",
        constants$9.const$1
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "rlDrawVertexArrayElements",
        constants$25.const$5
    );
}


