// Generated by jextract

package rayclj.rlgl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct rlDrawCall {
 *     int mode;
 *     int vertexCount;
 *     int vertexAlignment;
 *     unsigned int textureId;
 * };
 * }
 */
public class rlDrawCall {

    public static MemoryLayout $LAYOUT() {
        return constants$4.const$0;
    }
    public static VarHandle mode$VH() {
        return constants$4.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int mode;
     * }
     */
    public static int mode$get(MemorySegment seg) {
        return (int)constants$4.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int mode;
     * }
     */
    public static void mode$set(MemorySegment seg, int x) {
        constants$4.const$1.set(seg, x);
    }
    public static int mode$get(MemorySegment seg, long index) {
        return (int)constants$4.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void mode$set(MemorySegment seg, long index, int x) {
        constants$4.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle vertexCount$VH() {
        return constants$4.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int vertexCount;
     * }
     */
    public static int vertexCount$get(MemorySegment seg) {
        return (int)constants$4.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int vertexCount;
     * }
     */
    public static void vertexCount$set(MemorySegment seg, int x) {
        constants$4.const$2.set(seg, x);
    }
    public static int vertexCount$get(MemorySegment seg, long index) {
        return (int)constants$4.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void vertexCount$set(MemorySegment seg, long index, int x) {
        constants$4.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle vertexAlignment$VH() {
        return constants$4.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int vertexAlignment;
     * }
     */
    public static int vertexAlignment$get(MemorySegment seg) {
        return (int)constants$4.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int vertexAlignment;
     * }
     */
    public static void vertexAlignment$set(MemorySegment seg, int x) {
        constants$4.const$3.set(seg, x);
    }
    public static int vertexAlignment$get(MemorySegment seg, long index) {
        return (int)constants$4.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void vertexAlignment$set(MemorySegment seg, long index, int x) {
        constants$4.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle textureId$VH() {
        return constants$4.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int textureId;
     * }
     */
    public static int textureId$get(MemorySegment seg) {
        return (int)constants$4.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int textureId;
     * }
     */
    public static void textureId$set(MemorySegment seg, int x) {
        constants$4.const$4.set(seg, x);
    }
    public static int textureId$get(MemorySegment seg, long index) {
        return (int)constants$4.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void textureId$set(MemorySegment seg, long index, int x) {
        constants$4.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


