// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct BoneInfo {
 *     char name[32];
 *     int parent;
 * };
 * }
 */
public class BoneInfo {

    public static MemoryLayout $LAYOUT() {
        return constants$16.const$4;
    }
    public static MemorySegment name$slice(MemorySegment seg) {
        return seg.asSlice(0, 32);
    }
    public static VarHandle parent$VH() {
        return constants$16.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int parent;
     * }
     */
    public static int parent$get(MemorySegment seg) {
        return (int)constants$16.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int parent;
     * }
     */
    public static void parent$set(MemorySegment seg, int x) {
        constants$16.const$5.set(seg, x);
    }
    public static int parent$get(MemorySegment seg, long index) {
        return (int)constants$16.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void parent$set(MemorySegment seg, long index, int x) {
        constants$16.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


