// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("m0"),
            JAVA_FLOAT.withName("m4"),
            JAVA_FLOAT.withName("m8"),
            JAVA_FLOAT.withName("m12"),
            JAVA_FLOAT.withName("m1"),
            JAVA_FLOAT.withName("m5"),
            JAVA_FLOAT.withName("m9"),
            JAVA_FLOAT.withName("m13"),
            JAVA_FLOAT.withName("m2"),
            JAVA_FLOAT.withName("m6"),
            JAVA_FLOAT.withName("m10"),
            JAVA_FLOAT.withName("m14"),
            JAVA_FLOAT.withName("m3"),
            JAVA_FLOAT.withName("m7"),
            JAVA_FLOAT.withName("m11"),
            JAVA_FLOAT.withName("m15")
        ).withName("transform"),
        JAVA_INT.withName("meshCount"),
        JAVA_INT.withName("materialCount"),
        RuntimeHelper.POINTER.withName("meshes"),
        RuntimeHelper.POINTER.withName("materials"),
        RuntimeHelper.POINTER.withName("meshMaterial"),
        JAVA_INT.withName("boneCount"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("bones"),
        RuntimeHelper.POINTER.withName("bindPose")
    ).withName("Model");
    static final VarHandle const$1 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("meshCount"));
    static final VarHandle const$2 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("materialCount"));
    static final VarHandle const$3 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("meshes"));
    static final VarHandle const$4 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("materials"));
    static final VarHandle const$5 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("meshMaterial"));
}


