// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$118 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$118() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_BOOLEAN,
        MemoryLayout.structLayout(
            JAVA_INT.withName("baseSize"),
            JAVA_INT.withName("glyphCount"),
            JAVA_INT.withName("glyphPadding"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("id"),
                JAVA_INT.withName("width"),
                JAVA_INT.withName("height"),
                JAVA_INT.withName("mipmaps"),
                JAVA_INT.withName("format")
            ).withName("texture"),
            RuntimeHelper.POINTER.withName("recs"),
            RuntimeHelper.POINTER.withName("glyphs")
        ).withName("Font")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IsFontReady",
        constants$118.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "LoadFontData",
        constants$118.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("data"),
        JAVA_INT.withName("width"),
        JAVA_INT.withName("height"),
        JAVA_INT.withName("mipmaps"),
        JAVA_INT.withName("format")
    ).withName("Image"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GenImageFontAtlas",
        constants$118.const$4
    );
}


