// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "StopAutomationEventRecording",
        constants$29.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("frame"),
            JAVA_INT.withName("type"),
            MemoryLayout.sequenceLayout(4, JAVA_INT).withName("params")
        ).withName("AutomationEvent")
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "PlayAutomationEvent",
        constants$62.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "IsKeyPressed",
        constants$31.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "IsKeyPressedRepeat",
        constants$31.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "IsKeyDown",
        constants$31.const$3
    );
}


