// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$63 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$63() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "IsKeyReleased",
        constants$31.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IsKeyUp",
        constants$31.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "GetKeyPressed",
        constants$35.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetCharPressed",
        constants$35.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SetExitKey",
        constants$31.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "IsGamepadAvailable",
        constants$31.const$3
    );
}


