// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetWindowOpacity",
        constants$35.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SetWindowFocused",
        constants$29.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetWindowHandle",
        constants$35.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "GetScreenWidth",
        constants$35.const$5
    );
}


