// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SetSaveFileDataCallback",
        constants$33.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetLoadFileTextCallback",
        constants$33.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SetSaveFileTextCallback",
        constants$33.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "LoadFileData",
        constants$27.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "UnloadFileData",
        constants$33.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SaveFileData",
        constants$27.const$5
    );
}


