// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$142 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$142() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "LoadMaterials",
        constants$27.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("id"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("locs")
        ).withName("shader"),
        RuntimeHelper.POINTER.withName("maps"),
        MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("params")
    ).withName("Material"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "LoadMaterialDefault",
        constants$142.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BOOLEAN,
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_INT.withName("id"),
                MemoryLayout.paddingLayout(4),
                RuntimeHelper.POINTER.withName("locs")
            ).withName("shader"),
            RuntimeHelper.POINTER.withName("maps"),
            MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("params")
        ).withName("Material")
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "IsMaterialReady",
        constants$142.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_INT.withName("id"),
                MemoryLayout.paddingLayout(4),
                RuntimeHelper.POINTER.withName("locs")
            ).withName("shader"),
            RuntimeHelper.POINTER.withName("maps"),
            MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("params")
        ).withName("Material")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "UnloadMaterial",
        constants$142.const$5
    );
}


