// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$90 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$90() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "UnloadImage",
        constants$33.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_BOOLEAN,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("data"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("mipmaps"),
            JAVA_INT.withName("format")
        ).withName("Image"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ExportImage",
        constants$90.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("data"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("mipmaps"),
            JAVA_INT.withName("format")
        ).withName("Image"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ExportImageToMemory",
        constants$90.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ExportImageAsCode",
        constants$90.const$1
    );
}


