// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final VarHandle const$0 = constants$22.const$3.varHandle(MemoryLayout.PathElement.groupElement("ctxType"));
    static final VarHandle const$1 = constants$22.const$3.varHandle(MemoryLayout.PathElement.groupElement("ctxData"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("hResolution"),
        JAVA_INT.withName("vResolution"),
        JAVA_FLOAT.withName("hScreenSize"),
        JAVA_FLOAT.withName("vScreenSize"),
        JAVA_FLOAT.withName("vScreenCenter"),
        JAVA_FLOAT.withName("eyeToScreenDistance"),
        JAVA_FLOAT.withName("lensSeparationDistance"),
        JAVA_FLOAT.withName("interpupillaryDistance"),
        MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("lensDistortionValues"),
        MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("chromaAbCorrection")
    ).withName("VrDeviceInfo");
    static final VarHandle const$3 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("hResolution"));
    static final VarHandle const$4 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("vResolution"));
    static final VarHandle const$5 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("hScreenSize"));
}


