// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(TraceLogCallback.class, "apply", constants$26.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$26.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(LoadFileDataCallback.class, "apply", constants$27.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$27.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
}


