// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$99 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$99() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ImageRotateCCW",
        constants$33.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ImageColorTint",
        constants$95.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ImageColorInvert",
        constants$33.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ImageColorGrayscale",
        constants$33.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ImageColorContrast",
        constants$95.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ImageColorBrightness",
        constants$33.const$2
    );
}


