// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SaveFileTextCallback.class, "apply", constants$28.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$28.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "InitWindow",
        constants$29.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "CloseWindow",
        constants$29.const$4
    );
}


