// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final VarHandle const$0 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("colors"));
    static final VarHandle const$1 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("indices"));
    static final VarHandle const$2 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("animVertices"));
    static final VarHandle const$3 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("animNormals"));
    static final VarHandle const$4 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("boneIds"));
    static final VarHandle const$5 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("boneWeights"));
}


