// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$61 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$61() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "UnloadAutomationEventList",
        constants$33.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_BOOLEAN,
        MemoryLayout.structLayout(
            JAVA_INT.withName("capacity"),
            JAVA_INT.withName("count"),
            RuntimeHelper.POINTER.withName("events")
        ).withName("AutomationEventList"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ExportAutomationEventList",
        constants$61.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SetAutomationEventList",
        constants$33.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SetAutomationEventBaseFrame",
        constants$31.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "StartAutomationEventRecording",
        constants$29.const$4
    );
}


