// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$57 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$57() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetFileNameWithoutExt",
        constants$28.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "GetDirectoryPath",
        constants$28.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "GetPrevDirectoryPath",
        constants$28.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetWorkingDirectory",
        constants$35.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetApplicationDirectory",
        constants$35.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ChangeDirectory",
        constants$55.const$5
    );
}


