// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$160 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$160() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "IsAudioStreamProcessed",
        constants$159.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "PlayAudioStream",
        constants$159.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "PauseAudioStream",
        constants$159.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ResumeAudioStream",
        constants$159.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "IsAudioStreamPlaying",
        constants$159.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "StopAudioStream",
        constants$159.const$2
    );
}


