// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "EndDrawing",
        constants$29.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("offset"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("target"),
            JAVA_FLOAT.withName("rotation"),
            JAVA_FLOAT.withName("zoom")
        ).withName("Camera2D")
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "BeginMode2D",
        constants$41.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "EndMode2D",
        constants$29.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("position"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("target"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("up"),
            JAVA_FLOAT.withName("fovy"),
            JAVA_INT.withName("projection")
        ).withName("Camera3D")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "BeginMode3D",
        constants$41.const$4
    );
}


