// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$125 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$125() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "TextLength",
        constants$56.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "TextFormat",
        constants$28.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "TextSubtext",
        constants$125.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "TextReplace",
        constants$125.const$4
    );
}


