// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$122 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$122() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("baseSize"),
            JAVA_INT.withName("glyphCount"),
            JAVA_INT.withName("glyphPadding"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("id"),
                JAVA_INT.withName("width"),
                JAVA_INT.withName("height"),
                JAVA_INT.withName("mipmaps"),
                JAVA_INT.withName("format")
            ).withName("texture"),
            RuntimeHelper.POINTER.withName("recs"),
            RuntimeHelper.POINTER.withName("glyphs")
        ).withName("Font"),
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "GetGlyphIndex",
        constants$122.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("value"),
        JAVA_INT.withName("offsetX"),
        JAVA_INT.withName("offsetY"),
        JAVA_INT.withName("advanceX"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("data"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("mipmaps"),
            JAVA_INT.withName("format")
        ).withName("image")
    ).withName("GlyphInfo"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("baseSize"),
            JAVA_INT.withName("glyphCount"),
            JAVA_INT.withName("glyphPadding"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("id"),
                JAVA_INT.withName("width"),
                JAVA_INT.withName("height"),
                JAVA_INT.withName("mipmaps"),
                JAVA_INT.withName("format")
            ).withName("texture"),
            RuntimeHelper.POINTER.withName("recs"),
            RuntimeHelper.POINTER.withName("glyphs")
        ).withName("Font"),
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetGlyphInfo",
        constants$122.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y"),
        JAVA_FLOAT.withName("width"),
        JAVA_FLOAT.withName("height")
    ).withName("Rectangle"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("baseSize"),
            JAVA_INT.withName("glyphCount"),
            JAVA_INT.withName("glyphPadding"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("id"),
                JAVA_INT.withName("width"),
                JAVA_INT.withName("height"),
                JAVA_INT.withName("mipmaps"),
                JAVA_INT.withName("format")
            ).withName("texture"),
            RuntimeHelper.POINTER.withName("recs"),
            RuntimeHelper.POINTER.withName("glyphs")
        ).withName("Font"),
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetGlyphAtlasRec",
        constants$122.const$4
    );
}


