// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_BOOLEAN);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "WindowShouldClose",
        constants$30.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IsWindowReady",
        constants$30.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "IsWindowFullscreen",
        constants$30.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "IsWindowHidden",
        constants$30.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "IsWindowMinimized",
        constants$30.const$0
    );
}


