// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$121 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$121() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("baseSize"),
            JAVA_INT.withName("glyphCount"),
            JAVA_INT.withName("glyphPadding"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("id"),
                JAVA_INT.withName("width"),
                JAVA_INT.withName("height"),
                JAVA_INT.withName("mipmaps"),
                JAVA_INT.withName("format")
            ).withName("texture"),
            RuntimeHelper.POINTER.withName("recs"),
            RuntimeHelper.POINTER.withName("glyphs")
        ).withName("Font"),
        RuntimeHelper.POINTER,
        JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("Vector2"),
        JAVA_FLOAT,
        JAVA_FLOAT,
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DrawTextCodepoints",
        constants$121.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SetTextLineSpacing",
        constants$31.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "MeasureText",
        constants$121.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y")
    ).withName("Vector2"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("baseSize"),
            JAVA_INT.withName("glyphCount"),
            JAVA_INT.withName("glyphPadding"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("id"),
                JAVA_INT.withName("width"),
                JAVA_INT.withName("height"),
                JAVA_INT.withName("mipmaps"),
                JAVA_INT.withName("format")
            ).withName("texture"),
            RuntimeHelper.POINTER.withName("recs"),
            RuntimeHelper.POINTER.withName("glyphs")
        ).withName("Font"),
        RuntimeHelper.POINTER,
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "MeasureTextEx",
        constants$121.const$5
    );
}


