// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final VarHandle const$0 = constants$15.const$5.varHandle(MemoryLayout.PathElement.groupElement("value"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("id"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("locs")
        ).withName("shader"),
        RuntimeHelper.POINTER.withName("maps"),
        MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("params")
    ).withName("Material");
    static final VarHandle const$2 = constants$16.const$1.varHandle(MemoryLayout.PathElement.groupElement("maps"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("translation"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z"),
            JAVA_FLOAT.withName("w")
        ).withName("rotation"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("scale")
    ).withName("Transform");
    static final StructLayout const$4 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(32, JAVA_BYTE).withName("name"),
        JAVA_INT.withName("parent")
    ).withName("BoneInfo");
    static final VarHandle const$5 = constants$16.const$4.varHandle(MemoryLayout.PathElement.groupElement("parent"));
}


