// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$162 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$162() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "AttachAudioStreamProcessor",
        constants$161.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DetachAudioStreamProcessor",
        constants$161.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "AttachAudioMixedProcessor",
        constants$33.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "DetachAudioMixedProcessor",
        constants$33.const$4
    );
    static final MemorySegment const$4 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("5.0");
}


