// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final VarHandle const$0 = constants$7.const$3.varHandle(MemoryLayout.PathElement.groupElement("height"));
    static final VarHandle const$1 = constants$7.const$3.varHandle(MemoryLayout.PathElement.groupElement("mipmaps"));
    static final VarHandle const$2 = constants$7.const$3.varHandle(MemoryLayout.PathElement.groupElement("format"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("id"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("id"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("mipmaps"),
            JAVA_INT.withName("format")
        ).withName("texture"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("id"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("mipmaps"),
            JAVA_INT.withName("format")
        ).withName("depth")
    ).withName("RenderTexture");
    static final VarHandle const$4 = constants$8.const$3.varHandle(MemoryLayout.PathElement.groupElement("id"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("width"),
            JAVA_FLOAT.withName("height")
        ).withName("source"),
        JAVA_INT.withName("left"),
        JAVA_INT.withName("top"),
        JAVA_INT.withName("right"),
        JAVA_INT.withName("bottom"),
        JAVA_INT.withName("layout")
    ).withName("NPatchInfo");
}


