// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$68 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$68() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetMouseWheelMoveV",
        constants$38.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetMouseCursor",
        constants$31.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "GetTouchX",
        constants$35.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetTouchY",
        constants$35.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetTouchPosition",
        constants$36.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetTouchPointId",
        constants$37.const$0
    );
}


