// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$146 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$146() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_BOOLEAN.withName("hit"),
        MemoryLayout.paddingLayout(3),
        JAVA_FLOAT.withName("distance"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("point"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("normal")
    ).withName("RayCollision"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("position"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("direction")
        ).withName("Ray"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("min"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("max")
        ).withName("BoundingBox")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "GetRayCollisionBox",
        constants$146.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_BOOLEAN.withName("hit"),
        MemoryLayout.paddingLayout(3),
        JAVA_FLOAT.withName("distance"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("point"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("normal")
    ).withName("RayCollision"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("position"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("direction")
        ).withName("Ray"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("vertexCount"),
            JAVA_INT.withName("triangleCount"),
            RuntimeHelper.POINTER.withName("vertices"),
            RuntimeHelper.POINTER.withName("texcoords"),
            RuntimeHelper.POINTER.withName("texcoords2"),
            RuntimeHelper.POINTER.withName("normals"),
            RuntimeHelper.POINTER.withName("tangents"),
            RuntimeHelper.POINTER.withName("colors"),
            RuntimeHelper.POINTER.withName("indices"),
            RuntimeHelper.POINTER.withName("animVertices"),
            RuntimeHelper.POINTER.withName("animNormals"),
            RuntimeHelper.POINTER.withName("boneIds"),
            RuntimeHelper.POINTER.withName("boneWeights"),
            JAVA_INT.withName("vaoId"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("vboId")
        ).withName("Mesh"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("m0"),
            JAVA_FLOAT.withName("m4"),
            JAVA_FLOAT.withName("m8"),
            JAVA_FLOAT.withName("m12"),
            JAVA_FLOAT.withName("m1"),
            JAVA_FLOAT.withName("m5"),
            JAVA_FLOAT.withName("m9"),
            JAVA_FLOAT.withName("m13"),
            JAVA_FLOAT.withName("m2"),
            JAVA_FLOAT.withName("m6"),
            JAVA_FLOAT.withName("m10"),
            JAVA_FLOAT.withName("m14"),
            JAVA_FLOAT.withName("m3"),
            JAVA_FLOAT.withName("m7"),
            JAVA_FLOAT.withName("m11"),
            JAVA_FLOAT.withName("m15")
        ).withName("Matrix")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetRayCollisionMesh",
        constants$146.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_BOOLEAN.withName("hit"),
        MemoryLayout.paddingLayout(3),
        JAVA_FLOAT.withName("distance"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("point"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("normal")
    ).withName("RayCollision"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("position"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y"),
                JAVA_FLOAT.withName("z")
            ).withName("direction")
        ).withName("Ray"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("Vector3"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("Vector3"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y"),
            JAVA_FLOAT.withName("z")
        ).withName("Vector3")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetRayCollisionTriangle",
        constants$146.const$4
    );
}


