// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "IsWindowMaximized",
        constants$30.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IsWindowFocused",
        constants$30.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IsWindowResized",
        constants$30.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BOOLEAN,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "IsWindowState",
        constants$31.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "SetWindowState",
        constants$31.const$5
    );
}


