// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$44 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$44() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(2, MemoryLayout.structLayout(
                JAVA_FLOAT.withName("m0"),
                JAVA_FLOAT.withName("m4"),
                JAVA_FLOAT.withName("m8"),
                JAVA_FLOAT.withName("m12"),
                JAVA_FLOAT.withName("m1"),
                JAVA_FLOAT.withName("m5"),
                JAVA_FLOAT.withName("m9"),
                JAVA_FLOAT.withName("m13"),
                JAVA_FLOAT.withName("m2"),
                JAVA_FLOAT.withName("m6"),
                JAVA_FLOAT.withName("m10"),
                JAVA_FLOAT.withName("m14"),
                JAVA_FLOAT.withName("m3"),
                JAVA_FLOAT.withName("m7"),
                JAVA_FLOAT.withName("m11"),
                JAVA_FLOAT.withName("m15")
            ).withName("Matrix")).withName("projection"),
            MemoryLayout.sequenceLayout(2, MemoryLayout.structLayout(
                JAVA_FLOAT.withName("m0"),
                JAVA_FLOAT.withName("m4"),
                JAVA_FLOAT.withName("m8"),
                JAVA_FLOAT.withName("m12"),
                JAVA_FLOAT.withName("m1"),
                JAVA_FLOAT.withName("m5"),
                JAVA_FLOAT.withName("m9"),
                JAVA_FLOAT.withName("m13"),
                JAVA_FLOAT.withName("m2"),
                JAVA_FLOAT.withName("m6"),
                JAVA_FLOAT.withName("m10"),
                JAVA_FLOAT.withName("m14"),
                JAVA_FLOAT.withName("m3"),
                JAVA_FLOAT.withName("m7"),
                JAVA_FLOAT.withName("m11"),
                JAVA_FLOAT.withName("m15")
            ).withName("Matrix")).withName("viewOffset"),
            MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("leftLensCenter"),
            MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("rightLensCenter"),
            MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("leftScreenCenter"),
            MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("rightScreenCenter"),
            MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("scale"),
            MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("scaleIn")
        ).withName("VrStereoConfig")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "BeginVrStereoMode",
        constants$44.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "EndVrStereoMode",
        constants$29.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(2, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("m0"),
            JAVA_FLOAT.withName("m4"),
            JAVA_FLOAT.withName("m8"),
            JAVA_FLOAT.withName("m12"),
            JAVA_FLOAT.withName("m1"),
            JAVA_FLOAT.withName("m5"),
            JAVA_FLOAT.withName("m9"),
            JAVA_FLOAT.withName("m13"),
            JAVA_FLOAT.withName("m2"),
            JAVA_FLOAT.withName("m6"),
            JAVA_FLOAT.withName("m10"),
            JAVA_FLOAT.withName("m14"),
            JAVA_FLOAT.withName("m3"),
            JAVA_FLOAT.withName("m7"),
            JAVA_FLOAT.withName("m11"),
            JAVA_FLOAT.withName("m15")
        ).withName("Matrix")).withName("projection"),
        MemoryLayout.sequenceLayout(2, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("m0"),
            JAVA_FLOAT.withName("m4"),
            JAVA_FLOAT.withName("m8"),
            JAVA_FLOAT.withName("m12"),
            JAVA_FLOAT.withName("m1"),
            JAVA_FLOAT.withName("m5"),
            JAVA_FLOAT.withName("m9"),
            JAVA_FLOAT.withName("m13"),
            JAVA_FLOAT.withName("m2"),
            JAVA_FLOAT.withName("m6"),
            JAVA_FLOAT.withName("m10"),
            JAVA_FLOAT.withName("m14"),
            JAVA_FLOAT.withName("m3"),
            JAVA_FLOAT.withName("m7"),
            JAVA_FLOAT.withName("m11"),
            JAVA_FLOAT.withName("m15")
        ).withName("Matrix")).withName("viewOffset"),
        MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("leftLensCenter"),
        MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("rightLensCenter"),
        MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("leftScreenCenter"),
        MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("rightScreenCenter"),
        MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("scale"),
        MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("scaleIn")
    ).withName("VrStereoConfig"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("hResolution"),
            JAVA_INT.withName("vResolution"),
            JAVA_FLOAT.withName("hScreenSize"),
            JAVA_FLOAT.withName("vScreenSize"),
            JAVA_FLOAT.withName("vScreenCenter"),
            JAVA_FLOAT.withName("eyeToScreenDistance"),
            JAVA_FLOAT.withName("lensSeparationDistance"),
            JAVA_FLOAT.withName("interpupillaryDistance"),
            MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("lensDistortionValues"),
            MemoryLayout.sequenceLayout(4, JAVA_FLOAT).withName("chromaAbCorrection")
        ).withName("VrDeviceInfo")
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "LoadVrStereoConfig",
        constants$44.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "UnloadVrStereoConfig",
        constants$44.const$0
    );
}


