// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "GetMonitorWidth",
        constants$37.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "GetMonitorHeight",
        constants$37.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetMonitorPhysicalWidth",
        constants$37.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetMonitorPhysicalHeight",
        constants$37.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetMonitorRefreshRate",
        constants$37.const$0
    );
}


