// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetClipboardText",
        constants$35.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "EnableEventWaiting",
        constants$29.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "DisableEventWaiting",
        constants$29.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ShowCursor",
        constants$29.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "HideCursor",
        constants$29.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "IsCursorHidden",
        constants$30.const$0
    );
}


