// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "EnableCursor",
        constants$29.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DisableCursor",
        constants$29.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IsCursorOnScreen",
        constants$30.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b"),
            JAVA_BYTE.withName("a")
        ).withName("Color")
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ClearBackground",
        constants$40.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "BeginDrawing",
        constants$29.const$4
    );
}


