// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Material {
 *     Shader shader;
 *     MaterialMap* maps;
 *     float params[4];
 * };
 * }
 */
public class Material {

    public static MemoryLayout $LAYOUT() {
        return constants$16.const$1;
    }
    public static MemorySegment shader$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    public static VarHandle maps$VH() {
        return constants$16.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * MaterialMap* maps;
     * }
     */
    public static MemorySegment maps$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$16.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * MaterialMap* maps;
     * }
     */
    public static void maps$set(MemorySegment seg, MemorySegment x) {
        constants$16.const$2.set(seg, x);
    }
    public static MemorySegment maps$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$16.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void maps$set(MemorySegment seg, long index, MemorySegment x) {
        constants$16.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment params$slice(MemorySegment seg) {
        return seg.asSlice(24, 16);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


