// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct Vector4 Quaternion;
 * }
 */
public final class Quaternion extends Vector4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private Quaternion() {}
}


