// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct Rectangle {
 *     float x;
 *     float y;
 *     float width;
 *     float height;
 * };
 * }
 */
public class Rectangle {

    public static MemoryLayout $LAYOUT() {
        return constants$5.const$4;
    }
    public static VarHandle x$VH() {
        return constants$5.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float x;
     * }
     */
    public static float x$get(MemorySegment seg) {
        return (float)constants$5.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float x;
     * }
     */
    public static void x$set(MemorySegment seg, float x) {
        constants$5.const$5.set(seg, x);
    }
    public static float x$get(MemorySegment seg, long index) {
        return (float)constants$5.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void x$set(MemorySegment seg, long index, float x) {
        constants$5.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle y$VH() {
        return constants$6.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float y;
     * }
     */
    public static float y$get(MemorySegment seg) {
        return (float)constants$6.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float y;
     * }
     */
    public static void y$set(MemorySegment seg, float x) {
        constants$6.const$0.set(seg, x);
    }
    public static float y$get(MemorySegment seg, long index) {
        return (float)constants$6.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void y$set(MemorySegment seg, long index, float x) {
        constants$6.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle width$VH() {
        return constants$6.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float width;
     * }
     */
    public static float width$get(MemorySegment seg) {
        return (float)constants$6.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float width;
     * }
     */
    public static void width$set(MemorySegment seg, float x) {
        constants$6.const$1.set(seg, x);
    }
    public static float width$get(MemorySegment seg, long index) {
        return (float)constants$6.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void width$set(MemorySegment seg, long index, float x) {
        constants$6.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle height$VH() {
        return constants$6.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float height;
     * }
     */
    public static float height$get(MemorySegment seg) {
        return (float)constants$6.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float height;
     * }
     */
    public static void height$set(MemorySegment seg, float x) {
        constants$6.const$2.set(seg, x);
    }
    public static float height$get(MemorySegment seg, long index) {
        return (float)constants$6.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void height$set(MemorySegment seg, long index, float x) {
        constants$6.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


