// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct RenderTexture RenderTexture2D;
 * }
 */
public final class RenderTexture2D extends RenderTexture {

    // Suppresses default constructor, ensuring non-instantiability.
    private RenderTexture2D() {}
}


