// Generated by jextract

package rayclj.raylib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct Texture Texture2D;
 * }
 */
public final class Texture2D extends Texture {

    // Suppresses default constructor, ensuring non-instantiability.
    private Texture2D() {}
}


